package com.pdp.shared.error;

/**
 * 平台统一错误码。
 *
 * <p>使用稳定字符串键，禁止依赖枚举序号持久化。领域模块可定义自身错误码，
 * 但公共错误语义必须使用本枚举，保证 {@code application/problem+json} 的 {@code code} 字段一致。
 *
 * <p>命名约定：{@code DOMAIN.REASON}，例如 {@code WORKSPACE.NOT_FOUND}。
 */
public enum ErrorCode {

    // 通用
    VALIDATION_FAILED("VALIDATION.FAILED"),
    RESOURCE_NOT_FOUND("RESOURCE.NOT_FOUND"),
    FORBIDDEN("AUTH.FORBIDDEN"),
    UNAUTHORIZED("AUTH.UNAUTHORIZED"),
    CONFLICT("STATE.CONFLICT"),
    BUSINESS_RULE_VIOLATED("BUSINESS.RULE_VIOLATED"),
    PRECONDITION_FAILED("STATE.PRECONDITION_FAILED"),

    // 工作空间与权限
    WORKSPACE_NOT_FOUND("WORKSPACE.NOT_FOUND"),
    WORKSPACE_BOUNDARY_VIOLATION("WORKSPACE.BOUNDARY_VIOLATION"),
    WORKSPACE_ARCHIVED("WORKSPACE.ARCHIVED"),

    // 并发
    OPTIMISTIC_LOCK_CONFLICT("CONCURRENCY.OPTIMISTIC_LOCK"),
    STALE_REVISION("CONCURRENCY.STALE_REVISION"),

    // 持久化与数据源
    DATASOURCE_UNKNOWN_KEY("DATASOURCE.UNKNOWN_KEY"),
    DATASOURCE_SWITCH_IN_TRANSACTION("DATASOURCE.SWITCH_IN_TRANSACTION"),
    DATASOURCE_UNAUTHORIZED_ROUTE("DATASOURCE.UNAUTHORIZED_ROUTE"),
    DATABASE_CAPABILITY_REJECTED("DATABASE.CAPABILITY_REJECTED"),

    // 幂等
    IDEMPOTENCY_KEY_REUSED("IDEMPOTENCY.KEY_REUSED"),

    // 内部
    INTERNAL_ERROR("INTERNAL.ERROR"),
    SERVICE_UNAVAILABLE("AVAILABILITY.SERVICE_UNAVAILABLE");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
