engine.version=8.0.0
database.product=MYSQL
target.version=8.0.0
create.scripts=org/flowable/common/db/create/flowable.mysql.create.common.sql,org/flowable/db/create/flowable.mysql.create.engine.sql,org/flowable/db/create/flowable.mysql.create.history.sql
previous.version=7.2.2
previous.upgrade.scripts=org/flowable/db/upgrade/flowable.mysql.upgradestep.7202.to.8000.engine.sql,org/flowable/db/upgrade/flowable.mysql.upgradestep.7202.to.8000.history.sql
